language: python
dist: trusty

python:
  - "3.6"

services:
  - mysql

addons:
  postgresql: "9.5"
  hosts:
    - test_site
    - test_site_postgres

install:
  - sudo rm /etc/apt/sources.list.d/mongodb*.list
  - sudo rm /etc/apt/sources.list.d/docker.list
  - sudo apt-get install hhvm && rm -rf /home/travis/.kiex/
  - sudo apt-get purge -y mysql-common mysql-server mysql-client
  - nvm install v8.10.0

  - wget https://raw.githubusercontent.com/frappe/bench/master/playbooks/install.py

  - sudo python install.py --develop --user travis --without-bench-setup
  - sudo pip install -e ~/bench

  - rm $TRAVIS_BUILD_DIR/.git/shallow
  - cd ~/ && bench init frappe-bench --python $(which python) --frappe-path $TRAVIS_BUILD_DIR
  - cp -r $TRAVIS_BUILD_DIR/test_sites/test_site ~/frappe-bench/sites/
  - cp -r $TRAVIS_BUILD_DIR/test_sites/test_site_postgres ~/frappe-bench/sites/

before_script:
  - cd ~/frappe-bench
  - sed -i 's/9000/9001/g' sites/common_site_config.json
  - bench start &
  - sleep 10

jobs:
  include:
    - stage: Server Side Tests
      script:
        - mysql -u root -ptravis -e 'create database test_frappe'
        - echo "USE mysql;\nCREATE USER 'test_frappe'@'localhost' IDENTIFIED BY 'test_frappe';\nFLUSH PRIVILEGES;\n" | mysql -u root -ptravis
        - echo "USE mysql;\nGRANT ALL PRIVILEGES ON \`test_frappe\`.* TO 'test_frappe'@'localhost';\n" | mysql -u root -ptravis
        - bench --site test_site reinstall --yes
        - bench --site test_site setup-help
        - bench setup-global-help --root_password travis
        - bench --site test_site scheduler disable
        - bench --site test_site run-tests
      env: MariaDB
    - # stage
      script:
        - psql -c "CREATE DATABASE test_frappe;" -U postgres
        - psql -c "CREATE USER test_frappe WITH PASSWORD 'test_frappe';" -U postgres
        - bench --site test_site_postgres reinstall --yes
        - bench --site test_site_postgres setup-help
        - bench setup-global-help --db_type=postgres --root_password travis
        - bench --site test_site_postgres scheduler disable
        - bench --site test_site_postgres run-tests
      env: Postgres
