language: python
dist: trusty
sudo: required

python:
  - 2.7
  - 3.6

env:
  - DB=mariadb
  - DB=postgres

services:
  - mysql

addons:
  postgresql: "9.4"
  hosts:
    - test_site
    - test_site_postrgres

matrix:
  allow_failures:
  - python: 2.7
    env: DB=postgres
  fast_finish: true

install:
  - "./.travis/install.sh"

before_script:
  - cd ~/frappe-bench
  - sed -i 's/9000/9001/g' sites/common_site_config.json
  - bench start &
  - sleep 10
  - cd $TRAVIS_BUILD_DIR

script:
  - "./.travis/run-tests.sh"

after_script:
  - coveralls -b apps/frappe -d ../../sites/.coverage