name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"  
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
       include:
        - DB: "mariadb"
          TYPE: "server"
        - DB: "postgres"
          TYPE: "server"
        - DB: "mariadb"
          TYPE: "ui"

    services:
      mysql:
        image: mariadb:10.3
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: YES
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3

      postgres:
        image: postgres:9.5
        env:
          POSTGRES_PASSWORD: travis
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Clone
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Add to Hosts
        run: |
          echo "127.0.0.1 test_site" | sudo tee -a /etc/hosts
          echo "127.0.0.1 test_site_producer" | sudo tee -a /etc/hosts

      - name: Install Dependencies
        run: bash ${GITHUB_WORKSPACE}/.github/helper/install_dependencies.sh

      - name: Install
        run: bash ${GITHUB_WORKSPACE}/.github/helper/install.sh
        env:
          DB: ${{ matrix.DB }}
          TYPE: ${{ matrix.TYPE }}

      - name: Run Tests
        run: bash ${GITHUB_WORKSPACE}/.github/helper/run_tests.sh
        env:
          DB: ${{ matrix.DB }}
          TYPE: ${{ matrix.TYPE }}

      - name: Coverage
        run: |
          cd ~/frappe-bench/
          pip install coverage==4.5.4
          pip install python-coveralls
          coveralls -b ~/frappe-bench/apps/frappe -d ~/frappe-bench/sites/.coverage
        env:
          DB: ${{ matrix.DB }}
          TYPE: ${{ matrix.TYPE }}
