name: 'Style and Sanity checker'
on: [push, pull_request]

jobs:
  flake8:
    runs-on: ubuntu-latest

    steps:
      - name: 'Setup Python'
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
        run: pip install flake8 --quiet

      - name: 'Clone repo'
        uses: actions/checkout@v2

      - name: 'Run Flake8'
        env:
          PR_NUMBER: ${{ github.event.number }}
        run: |
          cd $GITHUB_WORKSPACE
          files=$(git diff --name-only --diff-filter=d $GITHUB_BASE_REF)
          flake8 $(echo $files | grep '.py$' | tr '\r\n' ' ') --count --select=E9,F63,F72,F82 --show-source --statistics
