name: Parallel Cypress Tests

on:
  pull_request:
    branches:
    - develop
    - version-12-hotfix
    - version-11-hotfix

jobs:
  test:
    name: Cypress run
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        # run 3 copies of the current job in parallel
        containers: [1, 2, 3]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: before_install
        run: |
          wget -O /tmp/wkhtmltox.tar.xz https://github.com/frappe/wkhtmltopdf/raw/master/wkhtmltox-0.12.3_linux-generic-amd64.tar.xz
          tar -xf /tmp/wkhtmltox.tar.xz -C /tmp
          sudo mv /tmp/wkhtmltox/bin/wkhtmltopdf /usr/local/bin/wkhtmltopdf
          sudo chmod o+x /usr/local/bin/wkhtmltopdf
          # install cups
          sudo apt-get install libcups2-dev

      - name: install
        run: |
          cd ~
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.1/install.sh | bash
          ls
          pwd
          source ./.nvm/nvm.sh
          nvm install v8.10.0

          git clone https://github.com/frappe/bench --depth 1
          pip install -e ./bench

          bench init frappe-bench --skip-assets --python $(which python) --frappe-path $GITHUB_WORKSPACE

          mkdir ~/frappe-bench/sites/test_site
          cp $TRAVIS_BUILD_DIR/.travis/$DB.json ~/frappe-bench/sites/test_site/site_config.json
          mysql -u root -e "SET GLOBAL character_set_server = 'utf8mb4'";
          mysql -u root -e "SET GLOBAL collation_server = 'utf8mb4_unicode_ci'";
          mysql -u root -e "CREATE DATABASE test_frappe";
          mysql -u root -e "CREATE USER 'test_frappe'@'localhost' IDENTIFIED BY 'test_frappe'";
          mysql -u root -e "GRANT ALL PRIVILEGES ON \`test_frappe\`.* TO 'test_frappe'@'localhost'";
          mysql -u root -e "UPDATE mysql.user SET Password=PASSWORD('travis') WHERE User='root'";
          mysql -u root -e "FLUSH PRIVILEGES";
          cd ./frappe-bench
          sed -i 's/watch:/# watch:/g' Procfile
          sed -i 's/schedule:/# schedule:/g' Procfile
          sed -i 's/socketio:/# socketio:/g' Procfile; fi
          sed -i 's/redis_socketio:/# redis_socketio:/g' Procfile; fi
          bench start &
          bench --site test_site reinstall --yes
          bench build --app frappe
          bench --site test_site execute frappe.utils.install.complete_setup_wizard
          bench --site test_site run-ui-tests frappe --headless --parallel
