name: Parallel Cypress Tests

on:
  pull_request:
    branches:
    - develop
    - version-12-hotfix
    - version-11-hotfix

jobs:
  test:
    name: Cypress run
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        # run 3 copies of the current job in parallel
        containers: [1]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install Redis
        uses: shogo82148/actions-setup-redis@v1

      - name: Install Mariadb
        uses: getong/mariadb-action@v1.1
        with:
          mariadb version: '10.4.10' # Optional, default value is "latest". The version of the MariaDB
          mysql root password: 'travis' # Required if "mysql user" is empty, default is empty.
          collation server: 'utf8mb4_unicode_ci'
          mysql user: 'test_frappe_consumer' # Required if "mysql root password" is empty, default is empty. The superuser for the specified database. Can use secrets, too
          mysql password: test_frappe

      - name: before_install
        run: |
          wget -O /tmp/wkhtmltox.tar.xz https://github.com/frappe/wkhtmltopdf/raw/master/wkhtmltox-0.12.3_linux-generic-amd64.tar.xz
          tar -xf /tmp/wkhtmltox.tar.xz -C /tmp
          sudo mv /tmp/wkhtmltox/bin/wkhtmltopdf /usr/local/bin/wkhtmltopdf
          sudo chmod o+x /usr/local/bin/wkhtmltopdf
          sudo apt-get install libcups2-dev

      - name: install bench
        run: |
          cd $HOME
          pip install frappe-bench

      - name: init bench
        run: |
          echo $HOME
          cd $HOME
          ls -l $GITHUB_WORKSPACE
          bench init frappe-bench --skip-assets --python $(which python) --frappe-path $GITHUB_WORKSPACE

          mkdir $HOME/frappe-bench/sites/test_site
          cp $GITHUB_WORKSPACE/.travis/consumer_db/mariadb.json $HOME/frappe-bench/sites/test_site/site_config.json

      - name: start bench
        run: |
          cd $HOME/frappe-bench
          sed -i 's/watch:/# watch:/g' Procfile
          sed -i 's/schedule:/# schedule:/g' Procfile
          sed -i 's/socketio:/# socketio:/g' Procfile;
          sed -i 's/redis_socketio:/# redis_socketio:/g' Procfile;
          bench start &

      - name: run test
        run: |
          cd $HOME/frappe-bench
          sudo systemctl start mysql
          systemctl status mysql.service
          bench --site test_site reinstall --force --yes
          bench setup requirements --node;
          bench build --app frappe
          bench --site test_site execute frappe.utils.install.complete_setup_wizard
          bench --site test_site run-ui-tests frappe --headless --parallel
