name: Frappe + MariaDB Tests
on: [push, pull_request]

jobs:
  mariadb-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          path: 'frappe'
      - uses: getong/mariadb-action@v1.1
        with:
          character set server: 'utf8mb4' # Optional, default value is 'utf8mb4'. The '--character-set-server' option for mysqld
          collation server: 'utf8mb4_unicode_ci' # Optional, default value is 'utf8mb4_general_ci'. The '--collation-server' option for mysqld
          mariadb version: '10.3.27' # Optional, default value is "latest". The version of the MariaDB
          mysql root password: 'travis'
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12.x'
      - name: Start Redis
        uses: supercharge/redis-github-action@1.1.0
        with:
          redis-version: 5
      - name: Set up bench for current push
        run: |
          pip install -U frappe-bench
          bench init frappe-bench --no-backups --skip-assets --python $(which python) --frappe-path $GITHUB_WORKSPACE/frappe --skip-redis-config-generation

          mkdir ./frappe-bench/sites/test_site ./frappe-bench/sites/test_site_producer
          cp $GITHUB_WORKSPACE/frappe/.travis/consumer_db/mariadb.json ./frappe-bench/sites/test_site/site_config.json
          cp $GITHUB_WORKSPACE/frappe/.travis/producer_db/mariadb.json ./frappe-bench/sites/test_site_producer/site_config.json

          DATABASE_SETUP_COMMANDS="CREATE DATABASE test_frappe_consumer;CREATE USER 'test_frappe_consumer'@'localhost' IDENTIFIED BY 'test_frappe_consumer';GRANT ALL PRIVILEGES ON \`test_frappe_consumer\`.* TO 'test_frappe_consumer'@'localhost';CREATE DATABASE test_frappe_producer;CREATE USER 'test_frappe_producer'@'localhost' IDENTIFIED BY 'test_frappe_producer';GRANT ALL PRIVILEGES ON \`test_frappe_producer\`.* TO 'test_frappe_producer'@'localhost';FLUSH PRIVILEGES;"
          mysql -u root -e $DATABASE_SETUP_COMMANDS

          cd ./frappe-bench
          sed -i 's/watch:/# watch:/g;s/schedule:/# schedule:/g;s/socketio:/# socketio:/g;/redis/d' ./Procfile

          bench set-redis-cache-host redis-cache:6379
          bench set-redis-queue-host redis-queue:6379
          bench set-redis-socketio-host redis-socketio:6379

          bench start &
          bench --site test_site reinstall --yes
          bench --site test_site_producer reinstall --yes

      - name: Run tests
        run: bench --verbose --site test_site run-tests --coverage

      - name: Coveralls
        run: |
          pip install coverage==4.5.4 python-coveralls
          coveralls -b apps/frappe -d ../../sites/.coverage
