name: test
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          path: 'frappe'
      - uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      - name: Check if running tests necessary
        run: |
          cd $GITHUB_WORKSPACE/frappe
          python ./.travis/roulette.py
          if [[ $? != 2 ]];then
            exit;
          fi
      - uses: actions/setup-node@v1
        with:
          python-version: '12.x'
      - name: Set up bench for current push
        run: |
          npm install -g yarn
          pip3 install -U frappe-bench
          bench init frappe-bench --no-backups --skip-assets --python $(which python) --frappe-path $GITHUB_WORKSPACE/frappe

          mkdir ~/frappe-bench/sites/test_site
          cp $GITHUB_WORKSPACE/frappe/.travis/consumer_db/$DB.json ~/frappe-bench/sites/test_site/site_config.json
          mkdir ~/frappe-bench/sites/test_site_producer
          cp $GITHUB_WORKSPACE/frappe/.travis/producer_db/$DB.json ~/frappe-bench/sites/test_site_producer/site_config.json

          mysql -u root -e "SET GLOBAL character_set_server = 'utf8mb4'"
          mysql -u root -e "SET GLOBAL collation_server = 'utf8mb4_unicode_ci'"

          mysql -u root -e "CREATE DATABASE test_frappe_consumer"
          mysql -u root -e "CREATE USER 'test_frappe_consumer'@'localhost' IDENTIFIED BY 'test_frappe_consumer'"
          mysql -u root -e "GRANT ALL PRIVILEGES ON \`test_frappe_consumer\`.* TO 'test_frappe_consumer'@'localhost'"

          mysql -u root -e "CREATE DATABASE test_frappe_producer"
          mysql -u root -e "CREATE USER 'test_frappe_producer'@'localhost' IDENTIFIED BY 'test_frappe_producer'"
          mysql -u root -e "GRANT ALL PRIVILEGES ON \`test_frappe_producer\`.* TO 'test_frappe_producer'@'localhost'"

          mysql -u root -e "UPDATE mysql.user SET Password=PASSWORD('travis') WHERE User='root'"
          mysql -u root -e "FLUSH PRIVILEGES"

          cd ./frappe-bench
          sed -i 's/watch:/# watch:/g' Procfile
          sed -i 's/schedule:/# schedule:/g' Procfile
          sed -i 's/socketio:/# socketio:/g' Procfile
          sed -i 's/redis_socketio:/# redis_socketio:/g' Procfile

          bench start &
          bench --site test_site reinstall --yes
          bench --site test_site_producer reinstall --yes

      - name: Run tests
        run: bench --verbose --site test_site run-tests --coverage

      - name: Coveralls
        run: |
          pip install coverage==4.5.4 python-coveralls
          coveralls -b apps/frappe -d ../../sites/.coverage
